// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnjnylsiazrwxsucvyfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuam55bHNpYXpyd3hzdWN2eWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTI4MzEsImV4cCI6MjA2NzE2ODgzMX0.dDIalxnmBndBY7ZYQQJMrzEnhjlv7_oa6kCenVN-5s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});